<?php

// The machine-readable form of the Localization section of CLAUDE.md.
//
// LanguageRules::getAdditionalRulesFromConfig() only falls back to the 'default'
// entry when the target locale has *no* entry of its own, so these are spread into
// every locale rather than left to the fallback. Locale keys are normalised with
// strtolower(), hence 'zh_tw' and not 'zh_TW'.
$rules = [
    '- This is a self-hosted database backup application aimed at developers and sysadmins.',

    // Terminology
    '- The nouns "backup", "restore" and "snapshot" (and their plurals) stay in English in every locale, including languages written in another script: Greek writes "το αρχείο backup", Traditional Chinese writes "Backup 檔案". Never replace them with a native equivalent such as "sauvegarde", "copia de seguridad", "instantané", "instantánea", "αντίγραφο ασφαλείας", "備份" or "快照". They are industry jargon developers use untranslated in every language.',
    '- The same applies to the wider infrastructure vocabulary this audience says in English rather than translates: dump, job, log, logs, token, endpoint, bucket, webhook, cron, timeout, worker, queue, agent, cluster, schema, checksum, hash, staging, timestamp. Keep them in Latin script in every locale and let the surrounding sentence inflect around them.',
    '- Everyday words are still translated normally: password, username, database, server, file, folder, settings, name, size, date, error, warning, enabled, disabled.',
    '- Only the noun stays in English. Where the source uses backup or restore as a verb, translate the verb naturally and keep the English noun: "Restore this snapshot to another server" becomes "Restaurer ce snapshot vers un autre serveur", never "Restore ce snapshot". Never leave an English verb sitting inside a sentence written in another language or script.',
    '- Follow the capitalization of the source term: "Download Snapshot" keeps a capital "Snapshot", while "the snapshot was deleted" keeps it lowercase.',
    '- Never translate product, protocol or technology names: MySQL, MariaDB, PostgreSQL, SQLite, Redis, Valkey, MongoDB, SQL Server, Firebird, S3, SFTP, SSH, SMB, Samba, Azure, Adminer, Docker, Kubernetes, Helm, Discord, Telegram, Slack, gzip, zstd.',

    // Structure that Laravel reads back
    '- Preserve every :placeholder token exactly as written (:count, :name, :provider). Do not translate them, do not move the colon, and do not add spaces inside them.',
    '- Preserve Laravel pluralization: every count the source resolves must still resolve. A source reading "{1} …|[2,*] …" covers 1 and everything above it, so the branch conditions you emit have to cover the same range with no gap.',

    // Presentation
    '- Never output the ASCII apostrophe (U+0027), the ASCII double quote (U+0022) or an ampersand. Blade escapes them into HTML entities that then show up verbatim in the UI. Use the typographic apostrophe U+2019, the quotation marks of the target language, and the word for "and".',
    '- These strings are UI labels for buttons, badges, table headers and form hints. Keep them at most as long as the English, and never add explanations the source does not have.',
    '- Match the source punctuation and capitalization style: a source without a trailing period keeps none, a source in sentence case stays in sentence case.',
];

return [
    // Language file directory. 'lang' for Laravel.
    'source_directory' => 'lang',

    // Source language for translations. lang/en.json is generated by
    // `php artisan translatable:export en` (see `make update-translation`).
    'source_locale' => 'en',

    // Disk for source checksum state.
    'state' => [
        'disk' => 'local',
    ],

    'ai' => [
        'provider' => 'anthropic',
        'model' => 'claude-sonnet-5',
        'api_key' => env('ANTHROPIC_API_KEY'),

        // Required. AIProvider::maxTokens() picks the Anthropic default from a model-name
        // regex that only knows claude-3-5-* and claude-3-7-*, so anything newer falls
        // through to 4096 output tokens. A chunk of ~150 strings needs far more than that,
        // and the response is silently truncated: the command saves whatever parsed and
        // reports success, so a locale ends up part-translated with no error.
        'max_tokens' => 32000,
    ],

    // Single-translator mode: 2+ entries here would enable consensus translation.
    'consensus' => [
        'translators' => [],
        'judge' => [],
    ],

    // Keys are English sentences, 258 of which contain a period. Flat storage keeps
    // "Version 1.2 released" from being nested into a "Version 1" object.
    'dot_notation' => true,

    'disable_plural' => false,

    'skip_locales' => ['en', 'persistent-strings'],

    'additional_rules' => [
        'default' => $rules,
        'fr' => [
            ...$rules,
            '- Use « » for quotation marks and the typographic apostrophe ’ (never \').',
            '- Address the user with "vous".',
            '- Give the English noun a French article and agreement: "le backup", "un snapshot", "les logs", "des jobs".',
        ],
        'es' => [
            ...$rules,
            '- Use « » for quotation marks.',
            '- Give the English noun a Spanish article and agreement: "el backup", "un snapshot", "los logs", "las queues".',
        ],
        'el' => [
            ...$rules,
            '- Use « » for quotation marks.',
            '- Leave the English terms in Latin script inside the Greek sentence and inflect the Greek around them: "το αρχείο backup", "τα logs", "η ουρά queue δεν είναι διαθέσιμη". Do not transliterate them into Greek letters.',
        ],
        'zh_tw' => [
            ...$rules,
            '- Use Traditional Chinese as written in Taiwan, with full-width punctuation and 「」 for quotation marks.',
            '- Keep the English terms in Latin script. Never write 備份, 快照 or 恢復 for backup, snapshot or restore, not even in a button label such as "Backup Now".',
            '- Separate a Latin technical term from the surrounding Chinese characters with a single space, as in "Backup 檔案" and "下載 Snapshot".',
        ],
    ],
];
