#!/usr/bin/env php
<?php

/**
 * MSSQL Database Dump Script
 *
 * Generates a SQL script with CREATE TABLE and INSERT statements.
 * Usage: php mssql-dump.php --host=HOST --port=PORT --user=USER --password=PASS --database=DB --output=FILE
 */
$options = getopt('', ['host:', 'port:', 'user:', 'password:', 'database:', 'output:']);

$required = ['host', 'port', 'user', 'password', 'database', 'output'];
foreach ($required as $opt) {
    if (! isset($options[$opt])) {
        fwrite(STDERR, "Missing required option: --{$opt}\n");
        exit(1);
    }
}

$host = $options['host'];
$port = (int) $options['port'];
$user = $options['user'];
$password = $options['password'];
$database = $options['database'];
$outputFile = $options['output'];

try {
    $dsn = "sqlsrv:Server={$host},{$port};Database={$database};TrustServerCertificate=true";
    $pdo = new PDO($dsn, $user, $password, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    ]);

    $output = fopen($outputFile, 'w');
    if (! $output) {
        throw new Exception("Cannot open output file: {$outputFile}");
    }

    fwrite($output, "-- MSSQL Dump generated by mssql-dump.php\n");
    fwrite($output, "-- Database: {$database}\n");
    fwrite($output, '-- Date: '.date('Y-m-d H:i:s')."\n\n");

    // Get all user tables
    $tables = $pdo->query("
        SELECT TABLE_NAME
        FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_TYPE = 'BASE TABLE'
        AND TABLE_CATALOG = '{$database}'
        ORDER BY TABLE_NAME
    ")->fetchAll(PDO::FETCH_COLUMN);

    foreach ($tables as $table) {
        fwrite($output, "-- Table: {$table}\n");

        // Generate DROP and CREATE TABLE
        $createTable = generateCreateTable($pdo, $table);
        fwrite($output, "IF OBJECT_ID('{$table}', 'U') IS NOT NULL DROP TABLE [{$table}];\nGO\n");
        fwrite($output, $createTable."\nGO\n\n");

        // Generate INSERT statements
        $rows = $pdo->query("SELECT * FROM [{$table}]")->fetchAll(PDO::FETCH_ASSOC);
        if (! empty($rows)) {
            $columns = array_keys($rows[0]);
            $columnList = '['.implode('], [', $columns).']';

            // Enable identity insert if table has identity column
            $hasIdentity = hasIdentityColumn($pdo, $table);
            if ($hasIdentity) {
                fwrite($output, "SET IDENTITY_INSERT [{$table}] ON;\nGO\n");
            }

            foreach ($rows as $row) {
                $values = array_map(fn ($v) => formatValue($v), $row);
                fwrite($output, "INSERT INTO [{$table}] ({$columnList}) VALUES (".implode(', ', $values).");\n");
            }
            fwrite($output, "GO\n");

            if ($hasIdentity) {
                fwrite($output, "SET IDENTITY_INSERT [{$table}] OFF;\nGO\n");
            }
            fwrite($output, "\n");
        }
    }

    fclose($output);
    exit(0);

} catch (Exception $e) {
    fwrite(STDERR, 'Error: '.$e->getMessage()."\n");
    exit(1);
}

function generateCreateTable(PDO $pdo, string $table): string
{
    $columns = $pdo->query("
        SELECT
            c.COLUMN_NAME,
            c.DATA_TYPE,
            c.CHARACTER_MAXIMUM_LENGTH,
            c.NUMERIC_PRECISION,
            c.NUMERIC_SCALE,
            c.IS_NULLABLE,
            c.COLUMN_DEFAULT,
            COLUMNPROPERTY(OBJECT_ID(c.TABLE_SCHEMA + '.' + c.TABLE_NAME), c.COLUMN_NAME, 'IsIdentity') as IS_IDENTITY
        FROM INFORMATION_SCHEMA.COLUMNS c
        WHERE c.TABLE_NAME = '{$table}'
        ORDER BY c.ORDINAL_POSITION
    ")->fetchAll(PDO::FETCH_ASSOC);

    $pk = $pdo->query("
        SELECT COLUMN_NAME
        FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
        WHERE OBJECTPROPERTY(OBJECT_ID(CONSTRAINT_SCHEMA + '.' + CONSTRAINT_NAME), 'IsPrimaryKey') = 1
        AND TABLE_NAME = '{$table}'
    ")->fetchAll(PDO::FETCH_COLUMN);

    $colDefs = [];
    foreach ($columns as $col) {
        $def = "[{$col['COLUMN_NAME']}] ".formatDataType($col);

        if ($col['IS_IDENTITY']) {
            $def .= ' IDENTITY(1,1)';
        }

        $def .= $col['IS_NULLABLE'] === 'NO' ? ' NOT NULL' : ' NULL';

        if ($col['COLUMN_DEFAULT'] !== null && ! $col['IS_IDENTITY']) {
            $def .= " DEFAULT {$col['COLUMN_DEFAULT']}";
        }

        $colDefs[] = $def;
    }

    if (! empty($pk)) {
        $colDefs[] = 'PRIMARY KEY (['.implode('], [', $pk).'])';
    }

    return "CREATE TABLE [{$table}] (\n    ".implode(",\n    ", $colDefs)."\n);";
}

function formatDataType(array $col): string
{
    $type = strtoupper($col['DATA_TYPE']);

    return match ($type) {
        'NVARCHAR', 'VARCHAR', 'NCHAR', 'CHAR' => $col['CHARACTER_MAXIMUM_LENGTH'] == -1
            ? "{$type}(MAX)"
            : "{$type}({$col['CHARACTER_MAXIMUM_LENGTH']})",
        'DECIMAL', 'NUMERIC' => "{$type}({$col['NUMERIC_PRECISION']},{$col['NUMERIC_SCALE']})",
        default => $type,
    };
}

function hasIdentityColumn(PDO $pdo, string $table): bool
{
    $result = $pdo->query("
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS c
        WHERE c.TABLE_NAME = '{$table}'
        AND COLUMNPROPERTY(OBJECT_ID(c.TABLE_SCHEMA + '.' + c.TABLE_NAME), c.COLUMN_NAME, 'IsIdentity') = 1
    ")->fetch();

    return $result !== false;
}

function formatValue($value): string
{
    if ($value === null) {
        return 'NULL';
    }
    if (is_bool($value)) {
        return $value ? '1' : '0';
    }
    if (is_int($value) || is_float($value)) {
        return (string) $value;
    }

    // Escape single quotes
    return "N'".str_replace("'", "''", $value)."'";
}
